{"name":"dockerfile-rs","vers":"0.1.0","deps":[],"cksum":"0b97cb6173f61575f5481fc28f93596c4c268f0ec8f650819603d2d3eecdbb55","features":{},"yanked":false,"links":null}
{"name":"dockerfile-rs","vers":"0.1.1","deps":[],"cksum":"fd9b7ebe2520b05c67292c0543b2f66dadeb4e6c0a172de9f38066c3d8f1a28a","features":{},"yanked":false,"links":null}
{"name":"dockerfile-rs","vers":"0.2.0","deps":[],"cksum":"f8e2cab491321e9000a89a3c5dc20091df066f038c9b1bb32b74eaaabe3e4b51","features":{},"yanked":false,"links":null}
